/**
 * What changed from one month to the next, and which entries explain it.
 *
 * "As despesas aumentaram" is not information — it is the beginning of a question.
 * The useful answer names the categories that moved and separates the part that will
 * repeat from the part that will not: a month that was expensive because of one
 * fridge is a different month from one that became expensive for good.
 */

import { countsInMonthlyTotals } from "@/lib/domain/monthlyTotals"
import { formatCentsBRL } from "@/lib/domain/money"
import type { Card, Category, Transaction } from "@/lib/types"
import type { MonthString } from "@/lib/domain/dateUtils"

export type Movement = { currentCents: number; previousCents: number; deltaCents: number }

export type CategoryMovement = Movement & {
  categoryId: string
  name: string
  icon: string
  iconUrl?: string
  color: string
}

export type MonthReview = {
  month: MonthString
  previousMonth: MonthString
  receitas: Movement
  despesas: Movement
  saldo: Movement
  /** Categories whose spending moved, biggest change first. */
  byCategory: CategoryMovement[]
  /** The part of the change that came from charges that repeat every month. */
  recurring: Movement
  /** The part that came from one-off spending — the fridge, the trip, the fine. */
  oneOff: Movement
  /** The largest one-off expenses of the month, the ones worth naming. */
  exceptional: Transaction[]
}

function movement(currentCents: number, previousCents: number): Movement {
  return { currentCents, previousCents, deltaCents: currentCents - previousCents }
}

function expenses(transactions: Transaction[], archivedCardsById: Map<string, Card>) {
  return transactions.filter(
    (t) => t.direction === "out" && countsInMonthlyTotals(t, archivedCardsById)
  )
}

function income(transactions: Transaction[], archivedCardsById: Map<string, Card>) {
  return transactions.filter(
    (t) => t.direction === "in" && countsInMonthlyTotals(t, archivedCardsById)
  )
}

function total(transactions: Transaction[]): number {
  return transactions.reduce((sum, t) => sum + t.amountCents, 0)
}

/** A charge that repeats: generated by a recurring rule, or an instalment already running. */
function repeats(t: Transaction): boolean {
  return !!t.recurringSeriesId || !!t.installmentGroupId
}

export function buildMonthReview(input: {
  month: MonthString
  previousMonth: MonthString
  current: Transaction[]
  previous: Transaction[]
  categories: Category[]
  archivedCardsById: Map<string, Card>
  /** How much of the month's spending an entry has to be to be called exceptional. */
  exceptionalShare?: number
}): MonthReview {
  const currentExpenses = expenses(input.current, input.archivedCardsById)
  const previousExpenses = expenses(input.previous, input.archivedCardsById)
  const currentIncome = income(input.current, input.archivedCardsById)
  const previousIncome = income(input.previous, input.archivedCardsById)

  const despesas = movement(total(currentExpenses), total(previousExpenses))
  const receitas = movement(total(currentIncome), total(previousIncome))
  const saldo = movement(
    receitas.currentCents - despesas.currentCents,
    receitas.previousCents - despesas.previousCents
  )

  const categoriesById = new Map(input.categories.map((c) => [c.id, c]))
  const byCategoryId = new Map<string, { current: number; previous: number }>()
  for (const t of currentExpenses) {
    const entry = byCategoryId.get(t.categoryId) ?? { current: 0, previous: 0 }
    entry.current += t.amountCents
    byCategoryId.set(t.categoryId, entry)
  }
  for (const t of previousExpenses) {
    const entry = byCategoryId.get(t.categoryId) ?? { current: 0, previous: 0 }
    entry.previous += t.amountCents
    byCategoryId.set(t.categoryId, entry)
  }

  const byCategory: CategoryMovement[] = [...byCategoryId]
    .map(([categoryId, { current, previous }]) => {
      const category = categoriesById.get(categoryId)
      return {
        categoryId,
        name: category?.name ?? "Sem categoria",
        icon: category?.icon ?? "Circle",
        iconUrl: category?.iconUrl,
        color: category?.color ?? "#64748b",
        ...movement(current, previous),
      }
    })
    .filter((c) => c.deltaCents !== 0)
    .sort((a, b) => Math.abs(b.deltaCents) - Math.abs(a.deltaCents))

  const recurring = movement(
    total(currentExpenses.filter(repeats)),
    total(previousExpenses.filter(repeats))
  )
  const oneOff = movement(
    total(currentExpenses.filter((t) => !repeats(t))),
    total(previousExpenses.filter((t) => !repeats(t)))
  )

  // Two conditions, because either alone gets it wrong: big enough to move the month,
  // and half again bigger than what that category spent outside its recurring charges
  // last month. Otherwise an ordinary grocery run in an expensive month is called
  // exceptional — the exact misreading this list exists to prevent — and comparing
  // against the category's total would hide a fridge behind the rent.
  const share = input.exceptionalShare ?? 0.15
  const UNUSUAL_FACTOR = 1.5
  const previousOneOffByCategory = new Map<string, number>()
  for (const t of previousExpenses) {
    if (repeats(t)) continue
    previousOneOffByCategory.set(
      t.categoryId,
      (previousOneOffByCategory.get(t.categoryId) ?? 0) + t.amountCents
    )
  }
  const exceptional = currentExpenses
    .filter((t) => !repeats(t))
    .filter((t) => despesas.currentCents > 0 && t.amountCents / despesas.currentCents >= share)
    .filter(
      (t) => t.amountCents > (previousOneOffByCategory.get(t.categoryId) ?? 0) * UNUSUAL_FACTOR
    )
    .sort((a, b) => b.amountCents - a.amountCents)
    .slice(0, 3)

  return { month: input.month, previousMonth: input.previousMonth, receitas, despesas, saldo, byCategory, recurring, oneOff, exceptional }
}

/**
 * One sentence saying where the difference came from.
 *
 * Written as a claim someone can check against the rest of the screen, not as a mood:
 * if it says the recurring charges held steady, the numbers above it have to agree.
 */
export function explainDespesas(review: MonthReview): string {
  const delta = review.despesas.deltaCents
  if (review.despesas.previousCents === 0) {
    return "Não há mês anterior com despesas para comparar."
  }
  if (Math.abs(delta) < review.despesas.previousCents * 0.05) {
    return "As despesas ficaram próximas do mês anterior."
  }

  const direction = delta > 0 ? "maiores" : "menores"
  const drivenByOneOff = Math.abs(review.oneOff.deltaCents) > Math.abs(review.recurring.deltaCents)

  if (drivenByOneOff) {
    const biggest = review.exceptional[0]
    const cause = biggest
      ? ` A maior parte vem de ${biggest.description.toLowerCase()} (${formatCentsBRL(biggest.amountCents)}).`
      : " A maior parte vem de gastos que não se repetem todo mês."
    return `As despesas foram ${formatCentsBRL(Math.abs(delta))} ${direction} que no mês anterior.${cause}`
  }

  return `As despesas foram ${formatCentsBRL(
    Math.abs(delta)
  )} ${direction} que no mês anterior, e a diferença está nas cobranças que se repetem todo mês.`
}
